version: "3.8"

services:
  redis-server:
    image: redis:6.0.5-alpine
    container_name: tokens
    command: redis-server --requirepass todovale
    ports:
      - "6379:6379"
    restart: always
    
